#! /bin/sh
# File          :  install.sh
# Created       :  Fri 23 Oct 2015 23:15:47
# Last Modified :  Sat 02 Jan 2016 23:16:28
# Maintainer    :  sharlatan, <sharlatanus@gmail.com>
# License       :  Same as Bash (GPL)
# Credits:
#
# Intallation of Install Working Invironment
#  _          _ 
# (_)        (_)
#  ___      ___ 
# | \ \ /\ / / |
# | |\ V  V /| |
# |_| \_/\_/ |_|
#               
ABS_PATH="$(dirname $(readlink -f $0))"
USR_PATH="$(echo ${ABS_PATH} | grep -oP "\/home\/\w+")"
SYS_CONF="${ABS_PATH}/sys.cfg"


if [[ $UID -ne 0 ]]; then
    echo Run as root
    exit 1
fi

# -=:[ FUNCTIONS ]:=-                                                        {{{
#
# Required function for convenient installation. 
#

__help() {
     cat << EOF
usage: $0 <OPTION>
    --help             Show this message.
    --all              Complete installation.

    --dot             Link all dotfiles to $USR_PATH.
    --set <SET_NAME>   Install set of packages.
EOF
 }

#__cmdp() {
#    #
#    # Determine if command exists
#    #
#    type "$1" &> /dev/null ;
#}

__pm() {
    #
    # Returns the packet manager name
    #
    if [[ -x "$(command -v yum)" ]]; then
        yum update
        xargs -a $1 yum install -yq
        exit 0
    elif [[ -x "$(command -v dnf)" ]]; then
        dnf update
        xargs -a $1 dnf install -yq
        exit 0
    elif [[ -x "$(command -v apt-get)" ]]; then
        apt-get update
        xargs -a $1 apt-get install -yq
        exit 0
    else 
        echo Non of yum, dnf, apg-get was found.
        exit 1
    fi
}

__pkg_install() {
    #
    # Determines the packet manager, update and install packages.
    # 
    source ${ABS_PATH}/cfg.sh
    local sets="$(grep -oP "[A-Z]+" ${ABS_PATH}/cfg.sh)"

    if [[ $# -eq 0 ]]; then
        echo Avialible sets:
        echo
        echo ${sets}
        echo
        exit 1
    fi
}

__dot_link() {
    #
    # Link all dot files to $(HOME)
    #
    for dot_file in $(ls "${ABS_PATH}/dotfiles"); do
        ln -sf "${ABS_PATH}/dotfiles/$dot_file" "${USR_PATH}/.$dot_file"
    done
}
# }}}

# -=:[ MAIN ]:=-{{{
#
# Meaty part of the installation
#

if [[ $# -eq 0 ]]; then
    __help
fi

for opt in $@; do
  case $opt in
    --help) 
        __help exit 0
        ;;
    --dots)
        __dot_link
        exit 0
        ;;
    --set)
        __pm
        # __pkg_install
        exit 0
        ;;
      esac
done
# }}}

