#! /usr/bin/env bash
# File          :  .bashrc
# Created       :  Mon 08 Dec 2014 19:31:26
# Last Modified :  Wed Mar 30 2016 06:07:22 sharlatan
# Maintainer    :  sharlatan, <sharlatanus@gmail.com>
# License       :  Same as Bash (GPL)
# Credits       :  See CREDITS section
#
# -=:[ DESCRIPTION ]:=-
#
# All setting for .bashrc file.
# <END OF # DESCRIPTION>-------------------------------------------------------

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi


# -=[ EXPORTS ]=-                                                            {{{
export HISTCONTROL=ignoredups:erasedups
export EDITOR=vim
#<END Of EXPORTS >-----------------------------------------------------------}}}

# -=:[ SETTINGS ]:=-                                                         {{{
# set vi like keyboard movement
set -o vi           # se

PROMPT_COMMAND='pwd'
PS1='[ $(if [ $? = 0 ]; then echo "\[\033[01;32m\]●";\
 else 2>/dev/null;\
 echo "\[\033[01;31m\]●\[\e[m\]"; fi) ][ \[\e[33m\]\u@\H\[\e[m\] ]:\$ '

# History hacks
shopt -s histappend
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
# <END OF # SETTINGS>--------------------------------------------------------}}}

#-=:[ FUNCTIONS ]:=-                                                          {{{
#-=[ fzf setup ]=---------------------------------------------------------------
# TODO add case condition > fd (-a -f)

# ---[ fzf
function fe() {
    # fe [fuzzy pattern] open the selected file with the default editor
    # -Bypass fuzzy finder if ther's only one match (--selected-1)
    # - Exit if ther's no match (--exit-0)

    cd
    local file
    file=$(fzf-tmux -d 20% --query="$1" --select-1 --exit-0)
    [ -n "$file" ] && ${EDITOR: -vim} "$file"
}

function fd() {
    #
    # fd - cd to selected directory (excluding hiden)
    #
    local dir
    dir=$(find ${1:-*} -path '*/\.' -prune \
        -o -type d -print 2> /dev/null | fzf-tmux -d 20% +m) &&
    cd "$dir"
}

function fda() {
    #
    # fda - cd to any (including hiden) directory
    #
    local dir
    dir=$(find ${1:-.} -type d 2> /dev/null | fzf-tmux -d 20% +m) &&
        cd "$dir"
}

function fdf() {
    #
    # fda cd into directory of the selected file
    #
    local file
    local dir
    file=$(fzf-tmux -d 20% +m -q "$1") && dir=$(dirname "$file") &&
        cd "$dir"
}
# --[ end of fzf ]--

# --[ percol ]--
function mp () {
    # Read man with percol
     tmux split-window 'man $(ls /usr/bin | percol)'
}
function m() {
    #function_body
    man $1 | percol
}
function gpom () {
    git push origin master
}

function show() {
    # Copy password from the list
    if [[ $# -ne 1 ]]; then
        echo Enter at least one argument
        exit 1
    fi
    grep $1 ~/Documents/txt/overrall | awk -FБ▀╝ '{print $3}' | tr -d '\n' | xclip
}

function mcd() { mkdir -p "$1" && cd "$1";}
#
#function lsd() {
#    # list of recently visited dirs
#
#    if [ -e /tmp/lsd ]; then
#        rm /tmp/lsd
#    else touch /tmp/lsd
#    fi
#
#    history|awk '$0 !~ /history/' | awk '$0 !~ /\"/'|awk '/cd \// || /cd \~/ ||
#        /pushd \// || /pushd \~/' | awk '{print $3}' |
#        sort -u | nl | tee /tmp/lsd
#
#    read -p "> " where
#    TOGO=$(sed -n "${where}p" /tmp/lsd | awk -F" " '{print $2}')
#    eval cd "$TOGO"
#}
#
#<END OF FUNCIONS>-----------------------------------------------------------}}}

#-=:[ ALIAS ]:=-                                                             {{{
alias c='clear'
alias em='emacs -nw'
alias aplay='ansible-playbook'

alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'

# ls
alias ls="ls -1p --color=auto"
alias l="ls -lhGgo"
alias ll="ls -lh"
alias la="ls -lhGgoA"
alias lt="ls -lhGgotr"
alias lS="ls -lhGgoSr"
alias l.="ls -lhGgod .*"
alias lhead="ls -lhGgo | head"
alias ltail="ls -lhGgo | tail"
alias lmore='ls -lhGgo | more'
#<END OF ALIAS>--------------------------------------------------------------}}}


#if [[ ! $TERM =~ screen ]]; then
#        exec tmux
#fi
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

#-=:[ CREDITS ]:=-{{{
# --[ GitHub
# https://github.com/junegunn/fzf
#<END OF CREDITS> }}}
